### ISSUE TITLE
Counter y libros

### ISSUE THREAD

**Issue by marcelobuergo** [pdepjm/2024-tp0-presentacion-NahuelMarek#5]
¿Cual es tu mapa de Counter y libro favorito?
¿Cuales recomendas?

**Comment by NahuelMarek** [comment]
Mi mapa favorito de counter es Mirage, y libro favorito no podría decir porque tengo varios. Recomiendo Nacidos de la bruma y cualquier libro de Brandon Sanderson (aunque no recomiendo leer Elantris como primer acercamiento al autor) y Amanecer Rojo de Pierce Brown
